import * as THREE from '../vendor/three.module.js';
const ctxStub = new Proxy({}, { get: (t, p) => (p === 'measureText' ? () => ({ width: 10 }) : () => {}) });
global.document = { createElement: () => ({ width: 0, height: 0, getContext: () => ctxStub, style: {} }) };
global.window = { devicePixelRatio: 1 };
const { Terrain } = await import('../src/terrain.js');
const { Track } = await import('../src/track.js');
const { Game } = await import('../src/game.js');
const terrain = new Terrain(); terrain.buildNatural();
const track = new Track(); track.build(2).buildHash(); track.setHeightsFromTerrain(terrain); terrain.carve(track);
terrain.buildBoulders({ add() {} }, track);
const menu = { showScreen() {}, showCountdown() {}, showNotice() {}, setResults() {}, updateHud() {}, setMinimap() {} };
const audio = new Proxy({}, { get: () => () => {} });
const game = new Game({ scene: new THREE.Scene(), camera: new THREE.PerspectiveCamera(), terrain, track, audio, menu, autopilot: true });
game.startRace();
let pickups = 0, uses = 0, maxHeld = 0;
const origGive = game.items.giveRandomItem.bind(game.items);
game.items.giveRandomItem = (c, p) => { if (origGive(c, p)) pickups++; };
const origUse = game.items.useItem.bind(game.items);
game.items.useItem = (c, cars) => { if (c.item) uses++; origUse(c, cars); };
for (let i = 0; i < 60 * 90; i++) game.update(1 / 60);
console.log('after 90s game time: pickups:', pickups, 'uses:', uses, 'held now:', game.cars.filter(c => c.item).length, 'active boxes:', game.items.boxes.filter(b => b.active).length, 'peels:', game.items.peels.length, 'rockets fired ok, stuns:', game.cars.filter(c => c.stunT > 0).length);
