import { chromium } from 'playwright';
const errors = [];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', (e) => errors.push(String(e)));
await page.goto('http://localhost:8125/', { waitUntil: 'networkidle' });
await page.waitForFunction(() => window.__sceneReady, { timeout: 20000 });
await page.waitForTimeout(8000);
await page.screenshot({ path: 'shots/g_fix14b_menu.png' });
const ballScreen = () => page.evaluate(() => {
  const g = window.__game.local();
  if (!g) return null;
  const v = new window.__THREE.Vector3(g.x, g.y, g.z).project(window.__camera);
  return [+(v.x * 0.5 + 0.5).toFixed(3), +(-v.y * 0.5 + 0.5).toFixed(3)];
});
await page.evaluate(() => window.__game.start());
await page.waitForFunction(() => window.__game.local(), { timeout: 5000 });
const s1 = await ballScreen();
await page.waitForTimeout(600);
const s2 = await ballScreen();
await page.waitForTimeout(1800);
const s3 = await ballScreen();
console.log('ball screen: +0.1s', s1, '→ +0.7s', s2, '→ +2.5s', s3);
const moved = Math.max(Math.hypot(s1[0]-s2[0], s1[1]-s2[1]), Math.hypot(s2[0]-s3[0], s2[1]-s3[1]));
console.log(`max step drift: ${(moved*100).toFixed(1)}% of screen`);
console.log(moved < 0.06 ? 'SEAMLESS' : 'VISIBLE REFRAME');
console.log(errors.length ? errors.join('\n') : 'NO ERRORS');
await browser.close();
