import { chromium } from 'playwright';
const errors = [];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', (e) => errors.push(String(e)));
await page.goto('http://localhost:8125/', { waitUntil: 'networkidle' });
await page.waitForFunction(() => window.__sceneReady, { timeout: 20000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/g_fix7_intro_mid.png' });
await page.waitForTimeout(5000);
await page.screenshot({ path: 'shots/g_fix7_intro_end.png' });
const a = await page.evaluate(() => window.__camInfo);
await page.waitForTimeout(6000);
const b = await page.evaluate(() => window.__camInfo);
await page.screenshot({ path: 'shots/g_fix7_intro_hold.png' });
const drift = Math.hypot(a.p[0]-b.p[0], a.p[1]-b.p[1], a.p[2]-b.p[2]);
console.log(`camera drift over 6s after intro: ${drift.toFixed(4)} m`);
console.log(drift < 0.01 ? 'HOLD OK' : 'STILL MOVING');
console.log(errors.length ? errors.join('\n') : 'NO ERRORS');
await browser.close();
